In [32]:
import numpy as np

In [33]:
A = [[1, 0, 0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0,  0,  0],
     [0, 1, 0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0,  0,  0],
     [0, 0, 0, 0, 1, 0,  0,  0, 0, 0, 0, 0, 0, 0,  0,  0],
     [0, 0, 0, 0, 0, 1,  0,  0, 0, 0, 0, 0, 0, 0,  0,  0],
     [0, 0, 1, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0,  0,  0],
     [0, 0, 0, 1, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0,  0,  0],
     [0, 0, 0, 0, 0, 0, -1,  0, 0, 0, 0, 0, 0, 0,  0,  0],
     [0, 0, 0, 0, 0, 0,  0, -1, 0, 0, 0, 0, 0, 0,  0,  0],
     [0, 0, 0, 0, 0, 0,  0,  0, 1, 0, 0, 0, 0, 0,  0,  0],
     [0, 0, 0, 0, 0, 0,  0,  0, 0, 1, 0, 0, 0, 0,  0,  0],
     [0, 0, 0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 1, 0,  0,  0],
     [0, 0, 0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 1,  0,  0],
     [0, 0, 0, 0, 0, 0,  0,  0, 0, 0, 1, 0, 0, 0,  0,  0],
     [0, 0, 0, 0, 0, 0,  0,  0, 0, 0, 0, 1, 0, 0,  0,  0],
     [0, 0, 0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0, -1,  0],
     [0, 0, 0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0,  0, -1]]
A = np.array(A)

In [34]:
B = [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,  0,  0,  0,  0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,  0,  0,  0,  0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,  0,  0,  0,  0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,  0,  0,  0,  0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,  0,  0,  0,  0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,  0,  0,  0,  0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1,  0,  0,  0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, -1,  0,  0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0, -1,  0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0, -1]]
B = np.array(B)

In [35]:
C = [[1, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0],
     [0, 0, 1,  0, 0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0],
     [0, 1, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0],
     [0, 0, 0, -1, 0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0],
     [0, 0, 0,  0, 1, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0],
     [0, 0, 0,  0, 0, 0, 1,  0, 0, 0, 0,  0, 0, 0, 0,  0],
     [0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0],
     [0, 0, 0,  0, 0, 0, 0, -1, 0, 0, 0,  0, 0, 0, 0,  0],
     [0, 0, 0,  0, 0, 0, 0,  0, 1, 0, 0,  0, 0, 0, 0,  0],
     [0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 1,  0, 0, 0, 0,  0],
     [0, 0, 0,  0, 0, 0, 0,  0, 0, 1, 0,  0, 0, 0, 0,  0],
     [0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0, -1, 0, 0, 0,  0],
     [0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0, 1, 0, 0,  0],
     [0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 1,  0],
     [0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0, 0, 1, 0,  0],
     [0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0,  0, 0, 0, 0, -1]]
C = np.array(C)

In [36]:
print(A@B@C@A)

[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]]


In [42]:
print(sum(sum(A@C@B@A == A@B@C@A))//256)

1
